### ISSUE TITLE
MM 2.21 again, now sees certificate expired, electron v19

### ISSUE THREAD

**Issue by sdetweil** [fewieden/MMM-Fuel#100]
0|mm     | MMM-Fuel: Failed to retrieve prices FetchError: request to https://creativecommons.tankerkoenig.de/json/list.php?lat=51.40488&lng=8.06148&rad=5&type=all&apikey=xxxxxx-xxxxx-xxxxx-xxxxx&sort=dist failed, reason: certificate has expired
0|mm     |     at ClientRequest.<anonymous> (/home/pi/MagicMirror/modules/MMM-Fuel/node_modules/node-fetch/lib/index.js:1491:11)
0|mm     |     at ClientRequest.emit (events.js:200:13)
0|mm     |     at TLSSocket.socketErrorListener (_http_client.js:402:9)
0|mm     |     at TLSSocket.emit (events.js:200:13)
0|mm     |     at emitErrorNT (internal/streams/destroy.js:91:8)
0|mm     |     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
0|mm     |     at processTicksAndRejections (internal/process/task_queues.js:84:9) {
0|mm     |   message: 'request to ' +
0|mm     |     'https://creativecommons.tankerkoenig.de/json/list.php?lat=51.40488&lng=8.06148&rad=5&type=all&apikey=xxxxxxx-xxxxx-xxxxx-xxxxx-xxxxx&sort=dist ' +
0|mm     |     'failed, reason: certificate has expired',
0|mm     |   type: 'system',
0|mm     |   errno: 'CERT_HAS_EXPIRED',
0|mm     |   code: 'CERT_HAS_EXPIRED'
0|mm     | }e:

same issue as fs/promises

**Comment by sdetweil** [comment]
we closed this as a mismatch of code somehow, upgrade install failed, sort of..
