### ISSUE TITLE
Load load load

### ISSUE THREAD

**Issue by Dzeyda** [fewieden/MMM-Fuel#113]
Kann mir bitte jemand helfen, es wird immer nur Lade angezeigt. Pleace Help me.

**Comment by fewieden** [comment]
@Dzeyda can you please share your config for MMM-Fuel? Don't forget to remove sensitive data like API keys.

Do you see any errors in the terminal or the browser console?

**Comment by Dzeyda** [comment]
![Screenshot_2023-07-30-21-04-40-667_com realvnc viewer android](https://github.com/fewieden/MMM-Fuel/assets/140757705/832c1ab2-138c-4036-a1d1-44dca3372d43)
![IMG_20230730_211100](https://github.com/fewieden/MMM-Fuel/assets/140757705/f458f4cf-01c3-464f-88c8-ae32cbfc8819)
Wer can See this Terminal?

**Comment by Dzeyda** [comment]
[01.08.2023 21:09.19.266] [LOG]   FetchError: request to https://creativecommons.tankerkoenig.de/json/list.php?lat=51.6246&lng=12.308&rad=5&sort=price&type=diesel&apikey=*************************************** failed, reason: certificate has expired
    at ClientRequest.<anonymous> (/home/pi/MagicMirror/modules/MMM-Fuel/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  type: 'system',
  errno: 'CERT_HAS_EXPIRED',
  code: 'CERT_HAS_EXPIRED'
}

**Comment by fewieden** [comment]
@Dzeyda it loads fine for me with your config

![image](https://github.com/fewieden/MMM-Fuel/assets/9334168/a9f7e761-c8b8-4aef-8dea-fd8cf52f3aeb)

Your system is refusing the HTTPS certificate from the API. This happened around two years ago already https://github.com/fewieden/MMM-Fuel/issues/77#issuecomment-945945569.

Which version of MagicMirror are you running?

**Comment by M1dn8** [comment]
Hey :) maybe someone could help me...my module didn't load any prices anymore, got a new API Key, deinstalled the modul and reinstalled it but nothing worked for me...here the Error part from my pm2 log after restart the mirror
thank you for any answer .)

0|mm     | [2024-11-17 13:46:12.064] [ERROR] MMM-Fuel: Failed to retrieve prices Error: Error no fuel radius prices
0|mm     |     at getPricesByRadius (/home/pi/MagicMirror/modules/MMM-Fuel/apis/tankerkoenig.js:128:15)
0|mm     |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
0|mm     |     at async Object.getData (/home/pi/MagicMirror/modules/MMM-Fuel/apis/tankerkoenig.js:288:36)
0|mm     |     at async Class.getData (/home/pi/MagicMirror/modules/MMM-Fuel/node_helper.js:104:26)

**Comment by fewieden** [comment]
@Dzeyda have you looked into the linked issue regarding the expired certificate? https://github.com/fewieden/MMM-Fuel/issues/113#issuecomment-1666935290
